language: python
dist: trusty

script:
    - python setup.py test

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
- coveralls

branches:
  except:
    - gh-pages

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
